config/routes.rb
MyApp1::Application.routes.draw do

  resources :payments

  resources :orders

  resources :line_items

  resources :carts
  
  resources :products do 
    get "search_results", :on => :collection
  end

  get "store/index"
  get "products/search"
  post "products/search"
  get "store/category"
 

  match '/auth/facebook/callback' => 'users#facebook_login'
  match '/auth/twitter/callback' => 'users#twitter_login'
  
  match 'confirm_payment' => 'payments#confirm'
  get "user_dashboard/index"

  get "view_page/index"
 
  post "users/user_tweet"
  

 get "admin/index"
 controller :sessions do
  get 'login' => :new

  post 'login' => :create

  delete 'logout' => :destroy
 end 

  resources :users do
   put 'upload', :on => :collection
end   

 root :to => 'store#index'

end

app/views/layouts/application.html.erb
	
	<!DOCTYPE html>
<html>
<html lang="en">
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
	<script src="http://code.jquery.com/jquery-latest.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  	 <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <meta name="description" content="Rails Sample App">  
    <meta name="author" content="">  
    
</head>

<body>
   
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      
		 <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
		 </a>
			<a class="brand" href="#">Magick Store</a>
			<div class="nav-collapse">
			<ul class="nav">
			<%if !session[:user_id].blank?%>
			<li><%= link_to 'Logout', login_path%></li>
      <%end%>
			<li><%= link_to "Browse Products", store_index_path %></li>
			
				<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories <b class="caret"></b>
                       <ul class="dropdown-menu"  aria-labelledby="dLabel" style="display" >  
											 
                            <li><%= link_to 'Grocery',store_category_path(:category=>'grocery')%></li> 
                           <li><%= link_to 'Home appliances',store_category_path(:category=>'Home appliances')%></li> 
                           <li><%= link_to 'Watch',store_category_path(:category=>'Watch')%></li> 
													  <li><%= link_to 'fruits',store_category_path(:category=>'fruits')%></li> 
														 <li><%= link_to 'stationery',store_category_path(:category=>'stationery')%></li> 
														 <li><%= link_to 'Grocery',store_category_path(:category=>'grocery')%></li> 
														                            </ul>  
                    <script type="text/javascript">  
        $(function() {$('.dropdown-toggle').dropdown()});
				</script>
										</li>  
										
					
                <li><%= link_to "Contact Us" %></li>
			<li><%= link_to "Cart" %></li>
		<%= form_tag :controller => 'products', :action => 'search', :method => 'get' do %>
     <li> <%= text_field_tag :search, params[:search], :id => 'search_field' %>
      <%= submit_tag "Search", :name => nil %></li>
			<% end %>
     </ul>
				 </div>
		 </div>
          </div>
           			
  <div class="container-fluid">
    <div class="row1-fluid">
      <div class="span9 offset3">
			<div class="align-center">
			<p> 
						 </p><%= yield %></div>
						 </div>
						 </div>
						 </div>
						 </div>
						 </div>
						 </div>
						 
      <div class="span3">
			 			<h2>About Us</h2>
       online store for all your needs
			 with your money to be valued.
			 We care for your wallet.
			 </div>
    </div>
  </div>
	</body>
</html>
	 
	